### the test for AddRequestHeader
GET http://localhost:8080/get
// 换成下面的，测试第二组
#GET http://localhost:8080/red/1
Accept: */*
Cache-Control: no-cache

### the test for AddRequestParameter
GET http://localhost:8080/get
Accept: */*
Cache-Control: no-cache
// 打开注释测试第二组
#Host: www.fatal.com

### the test for AddResponseHeader
GET http://localhost:8080/response-headers
Accept: */*
Cache-Control: no-cache
// 打开注释测试第二组
#Host: www.fatal.com

### the test for DedupeResponseHeader GatewayFilter and RemoveResponseHeader GatewayFilter
GET http://localhost:8080/response-headers
Accept: */*
Cache-Control: no-cache

### the test for Hystrix GatewayFilter and CircuitBreaker GatewayFilter
GET http://localhost:8080/consumingserviceendpoint
Accept: */*
Cache-Control: no-cache

### the test for FallbackHeaders GatewayFilter
GET http://localhost:8080/ingredients/a/b
Accept: */*
Cache-Control: no-cache

### the test for MapRequestHeader GatewayFilter, PreserveHostHeader GatewayFilter,
# RequestRateLimiter GatewayFilter, RemoveRequestHeader GatewayFilter，SaveSession GatewayFilter
# and RedirectTo GatewayFilter
GET http://localhost:8080/get
Accept: */*
Cache-Control: no-cache

### the test for PrefixPath GatewayFilter
GET http://localhost:8080/hello
Accept: */*
Cache-Control: no-cache

### the test for RemoveRequestParameter GatewayFilter
GET http://localhost:8080/remove-request-parameter?name=fatal
Accept: */*
Cache-Control: no-cache

### the test for RewritePath GatewayFilter
GET http://localhost:8080/foo/red/blue
Accept: */*
Cache-Control: no-cache

### the test for RewriteResponseHeader GatewayFilter and SecureHeaders GatewayFilter
GET http://localhost:8080/headers
Accept: */*
Cache-Control: no-cache
Host: www.rewriteresponseheader.org

###
