### the test for AddRequestHeader
GET http://localhost:8080/get
// 换成下面的，测试第二组
#GET http://localhost:8080/red/1
Accept: */*
Cache-Control: no-cache

### the test for AddRequestParameter
GET http://localhost:8080/get
Accept: */*
Cache-Control: no-cache
// 打开注释测试第二组
#Host: www.fatal.com

### the test for AddResponseHeader
GET http://localhost:8080/response-headers
Accept: */*
Cache-Control: no-cache
// 打开注释测试第二组
#Host: www.fatal.com

### the test for DedupeResponseHeader
GET http://localhost:8080/response-headers
Accept: */*
Cache-Control: no-cache

###